// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vjortdokrcuxqeumhhis.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZqb3J0ZG9rcmN1eHFldW1oaGlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyMDM4MDIsImV4cCI6MjA3MTc3OTgwMn0.6r9-xQjKRTY9jNX2Q5A8NFaZMcaWYxmyTNA2nTUZNJc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});